# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_auto_20160523_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='rests',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rests',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
