# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='classic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cruises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='excursions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_forkids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_gastronomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_political',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_segway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thematic_street_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('perigrafh', models.TextField(blank=True)),
                ('timetable', models.TextField(blank=True)),
                ('diarkeia', models.CharField(max_length=128)),
                ('kostos', models.CharField(max_length=128)),
                ('private_group', models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('GROUP', 'group')], max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to='tours/static/tours/img/logo')),
                ('photo', models.FileField(blank=True, null=True, upload_to='tours/static/tours/img/photo')),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='thematic_street_art',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='thematic_segway',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='thematic_political',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='thematic_photo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='thematic_gastronomy',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='thematic_forkids',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='excursions',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='cruises',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='classic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
