# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thematic_forkids',
            new_name='thematic_kids_and_family',
        ),
    ]
