# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20160608_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
