# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='tour',
            name='diarkeia',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='tour',
            name='kostos',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
