# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_kouzina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kouzina',
            new_name='Bar_Restaurant',
        ),
    ]
