# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_afrikanikh_asiatikh_brunch_burger_burger_amerikanikh_ellhnikh_paradosiakh_falafes_fish_fusion_gallik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rests',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
