# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_auto_20160603_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rests',
            name='price',
            field=models.CharField(blank=True, choices=[('-10', 'ews 10 eurw'), ('10-20', '10 me 20 eurw'), ('20-30', '20 me 30 eurw'), ('30-40', '30 me 40 eurw'), ('40-50', '40 me 50 eurw'), ('50-', '50 eurw kai panw')], max_length=30),
        ),
    ]
