# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delicatessen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kosmhma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Moda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('perioxh', models.CharField(blank=True, max_length=128)),
                ('periferia', models.CharField(blank=True, max_length=128)),
                ('dieuthinsh', models.CharField(blank=True, max_length=128)),
                ('stigma', models.URLField(blank=True)),
                ('butlair_link', models.URLField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('thl_mail', models.CharField(blank=True, max_length=128)),
                ('perigrafh', models.TextField(blank=True)),
                ('wrario', models.TextField(blank=True)),
                ('greek_design', models.NullBooleanField()),
                ('handmade', models.NullBooleanField()),
                ('not_expensive', models.NullBooleanField()),
                ('gift', models.NullBooleanField()),
                ('traditional', models.NullBooleanField()),
                ('kids', models.NullBooleanField()),
                ('men', models.NullBooleanField()),
                ('women', models.NullBooleanField()),
                ('ceramics', models.NullBooleanField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='shopping/static/tours/img/logo')),
                ('photo', models.FileField(blank=True, null=True, upload_to='shopping/static/tours/img/photo')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='moda',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Shop'),
        ),
        migrations.AddField(
            model_name='kosmhma',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Shop'),
        ),
        migrations.AddField(
            model_name='delicatessen',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Shop'),
        ),
    ]
