# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='shopping/static/shopping/img/logo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='shopping/static/shopping/img/photo'),
        ),
    ]
